Repository EASYPEACH/shroop-admin, pull requests merged in 2023-09, with the labels that each got.

#4 Feat: 프론트에 신고 API를 연동했다
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/dto/response/ReportResponse.java
  frontend/src/views/report/ReportDetailsView.vue
  frontend/src/views/report/ReportView.vue
Labels: 기능개발, 백엔드, 프론트엔드

#9 Refactor: 프론트에서 신고하기 데이터 가져오는 시점을 변경했다
  frontend/src/plugins/vuetify.js
  frontend/src/views/report/ReportDetailsView.vue
  frontend/src/views/report/ReportView.vue
Labels: 리팩토링, 백엔드, 프론트엔드

#17 Feat: 카테고리 API를 구현했다
  backend/src/main/java/com/easypeach/shroopadmin/modules/global/request/SearchRequest.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/controller/CategoryController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/domain/Category.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/request/CategoryRequest.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/CategoryResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/PageCategoryResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/exception/CategoryDeleteException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/exception/CategoryNotExistException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/CategoryRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/service/CategoryService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/controller/MediateController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/controller/ReportController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/service/ReportService.java
Labels: 기능개발, 백엔드

#19 Feat: 관리자 회원 관리 기능 구현
  backend/src/main/java/com/easypeach/shroopadmin/infra/s3/service/S3UploadService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/log/UserLogRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/dto/response/MemberInfo.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/service/MemberService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/secession/BlackMember.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/secession/BlackMemberRepository.java
  frontend/src/views/account/AccountView.vue
  frontend/src/views/account/UserDetailsView.vue
  frontend/src/views/account/UserEditView.vue
Labels: 기능개발, 백엔드

#20 Feat: 프론트에 카테고리 API를 연동했다
  backend/src/main/java/com/easypeach/shroopadmin/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/domain/Category.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/exception/DuplicateCategoryException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/CategoryRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/service/CategoryService.java
  frontend/src/components/Modal/CategoryCreateModal.vue
  frontend/src/components/Modal/CategoryUpdateModal.vue
  frontend/src/components/NavigationBar.vue
  frontend/src/router/index.js
  frontend/src/views/catogory/CategoryView.vue
Labels: 기능개발, 백엔드, 프론트엔드

#14 Feat: 관리자 인증인가 jwt 구현
  backend/build.gradle
  backend/src/main/java/com/easypeach/shroopadmin/infra/config/EncoderConfig.java
  backend/src/main/java/com/easypeach/shroopadmin/infra/config/WebConfig.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/exception/InvalidTokenException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/exception/NotAuthrizedUserException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/presentation/AuthenticationPrincipal.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/presentation/AuthenticationPrincipalArgumentResolver.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/presentation/AuthorizationExtractor.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/service/JwtInterceptor.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/service/JwtProvider.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/dto/request/MemberSignInRequest.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/exception/UnAthoriazedException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/service/MemberService.java
Labels: 기능개발, 백엔드

#25 Feat: 상품 관리 기능 구현
  backend/build.gradle
  backend/src/main/java/com/easypeach/shroopadmin/ShroopadminApplication.java
  backend/src/main/java/com/easypeach/shroopadmin/infra/config/QuerydslConfig.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/like/controller/LikeController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/like/domain/LikeRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/like/service/LikeService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/likes/domain/Likes.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/likes/domain/LikesRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/controller/CategoryController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/request/SearchRequest.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/MemberResonse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/ProductCreatedResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/ProductImgResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/ProductOneImgResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/exception/ProductException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/exception/ProductImgLengthException.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/ProductImgRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/ProductRepositoryCustom.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/respository/ProductRepositoryCustomImpl.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/service/CategoryService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/transaction/domain/TransactionRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/transaction/domain/TransactionStatus.java
  frontend/src/components/Modal/PlainModal.vue
  frontend/src/consts/status.js
  frontend/src/views/product/ProductDetailsView.vue
  frontend/src/views/product/ProductView.vue
  frontend/src/views/product/RegistProductView.vue
Labels: 개발환경 세팅, UI/UX, 백엔드, 프론트엔드

#26 Fix: 프리플라이트 요청 검증 제외
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/service/JwtInterceptor.java
Labels: 버그, 백엔드

#27 Feat: 인증/인가 API 프론트 연동
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/auth/presentation/AuthorizationExtractor.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/service/MemberService.java
  frontend/src/layouts/default/View.vue
  frontend/src/router/index.js
  frontend/src/store/useCheckLogin.js
  frontend/src/views/LoginView.vue
Labels: 기능개발, 프론트엔드

#30 Fix: ui 개선
  frontend/.eslintrc.js
  frontend/jsconfig.json
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/components/Form/index.js
  frontend/src/components/Title/MainTitle.vue
  frontend/src/components/Title/index.js
  frontend/src/layouts/default/View.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/src/router/index.js
  frontend/src/views/HomeView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/account/AccountView.vue
  frontend/src/views/account/UserDetailsView.vue
  frontend/src/views/catogory/CategoryView.vue
  frontend/src/views/mediate/MediateDetailsView.vue
  frontend/src/views/mediate/MediateView.vue
  frontend/src/views/product/ProductView.vue
  frontend/src/views/product/RegistProductView.vue
  frontend/src/views/report/ReportDetailsView.vue
  frontend/src/views/report/ReportView.vue
Labels: 리팩토링, 프론트엔드

#31 Refactor: report 엔티티 수정했다
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/domain/ReportRepository.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/dto/response/MediateResponse.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/dto/response/ReportResponse.java
Labels: 리팩토링, 백엔드

#33 Feat: 신고,중재 상세 페이지에서 회원을 차단할 수 있도록 추가한다
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/dto/response/ReportResponse.java
  frontend/src/views/report/ReportDetailsView.vue
Labels: 기능개발, 백엔드, 프론트엔드

#37 Refactor: blacklist 엔티티를 제거했다
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/domain/BlackList.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/report/domain/BlackListRepository.java
Labels: 리팩토링, 백엔드

#40 Fix: 관리자 상품관리 폭조절
  frontend/src/views/product/ProductView.vue
Labels: UI/UX, 프론트엔드

#42 Refactor: Entity 및 ENUM 통일
  backend/src/main/java/com/easypeach/shroopadmin/modules/likes/domain/Likes.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/DuplicateCheckType.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/member/domain/ShroopMember.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/transaction/domain/Transaction.java
  backend/src/main/java/com/easypeach/shroopadmin/modules/transaction/domain/TransactionStatus.java
Labels: 리팩토링, 백엔드

#44 Refactor: 거래 상태를 수정했다
  backend/src/main/java/com/easypeach/shroopadmin/modules/transaction/domain/TransactionStatus.java
Labels: 리팩토링, 백엔드
